name: CI MLflow

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3
      
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.7

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mlflow-env
        environment-file: MLProject/conda.yaml
        auto-activate-base: false

    - name: Check Env
      run: |
        python --version
        conda --version

    - name: Run MLflow Project
      shell: bash -l {0}
      run: |
        cd MLProject
        mlflow run .

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: behavior-classifier
        path: MLProject/mlruns

    - name: Get latest run_id
      id: get_run_id
      run: |
        RUN_ID=$(ls -t MLProject/mlruns/0 | head -n 1)
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    - name: Install Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install git-lfs -y
        git lfs install

    - name: Configure Git Identity
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Debug Git Remote
      run: |
        git remote -v
        git config --list

    - name: Track and commit model to Github LFS branch
      if: ${{ steps.get_run_id.outputs.run_id != '' }}
      run: |
        set -e  # ⛑️ Tambahan: hentikan job jika ada perintah gagal

        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        # Track model files via LFS
        git lfs track "model_artifacts/**/*.pkl"
        echo "*.pkl" >> .gitattributes

        # Salin model dari mlruns ke folder baru
        mkdir -p model_artifacts
        cp -r MLProject/mlruns/0/${{ steps.get_run_id.outputs.run_id }}/artifacts/model model_artifacts/

        git add .gitattributes
        git add model_artifacts/
        git commit -m "Add model to LFS from run ${{ steps.get_run_id.outputs.run_id }}"

        # Update remote dengan autentikasi token
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

        # Push ke branch baru
        git push origin HEAD:lfs-model-${{ steps.get_run_id.outputs.run_id }}

    - name: Build Docker image
      if: ${{ steps.get_run_id.outputs.run_id != '' }}
      shell: bash -l {0}
      run: |
        cd MLProject
        mlflow models build-docker \
          --model-uri runs:/${{ steps.get_run_id.outputs.run_id }}/model \
          --name behavior-classifier

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Tag Docker Image
      run : |
        docker tag behavior-classifier:latest ${{ secrets.DOCKER_USERNAME }}/behavior-classifier:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/behavior-classifier:latest
